sudo: false
cache: bundler
language: ruby
addons:
  apt:
    packages:
    - libgecode-dev
rvm:
- "2.0"
- "2.1"
- "2.2"
gemfile:
- gemfiles/default.gemfile
- gemfiles/master.gemfile
env:
  global:
  - USE_SYSTEM_GECODE=true
before_install: "gem install bundler"
script: bundle exec rake test
